# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_list_shared_with'),
        ('lists', '0005_remove_duplicates'),
    ]

    operations = [
    ]
